# Generated by Django 5.2.3 on 2025-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Individual', 'individual'), ('Driver', 'driver'), ('HealthAdmin', 'health_admin'), ('DriverAdmin', 'driver_admin'), ('Doctor', 'doctor')], max_length=100),
        ),
    ]
