# Generated by Django 5.1.6 on 2025-04-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
