# Generated by Django 5.2.3 on 2025-07-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_alter_ambulance_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Non-Urgent', 'Non-Urgent'), ('Routine', 'Routine'), ('Low', 'Low')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
