# Generated by Django 5.1.6 on 2025-05-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_remove_ambulancerequest_pickup_location_and_more'),
        ('users', '0003_organization_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driverprofile'),
        ),
    ]
